from Searchbyqualification.printOptions.printOptions import print_module
from Searchbyqualification.studentRegistration.studentRegistration import student_registration
from Searchbyqualification.studentSearch.studentSearch import search